var h1= document.createElement('h1');
var content=document.createElement('div');
var header=document.createElement('div');
var footer=document.createElement('div');
var main=document.createElement('div');
var leftcol=document.createElement('div');
var sitecontent=document.createElement('div');
content.className='site-content';
header.className='site-header';
footer.className='site-footer';
main.className='site-main';
leftcol.className='site-leftcol';
h1.className='site-title';
sitecontent.className='site-sitecontent';
h1.innerHTML='Привет';
document.body.appendChild(header);
document.body.appendChild(content);
document.body.appendChild(footer);
content.appendChild(h1);
content.appendChild(leftcol);
content.appendChild(sitecontent);